### ISSUE TITLE
Can't properly set position of modal

### ISSUE THREAD

**Issue by Baldi-OG** [fujaba/fulibFx#116]
**Describe the bug**
It seem that it is not possible to set the X and Y position of a modal. Trying with an event handler sometimes (!?) moves the modal but its not reliable. 

**To Reproduce**
1. Create modal
```java

  //

    @OnInit
    public void init() {
        modalStage.setX(someXPosition);
        modalStage.setY(someYPosition);
    }

  //

```

3. init and show it using modals.show()
``` java
modals
             .modal(componentProviderget())
             .show();
```

4. See that it did not move to the set position

**Expected behavior**
It should move to the set position

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Using Hyprland for wayland

**Comment by LeStegii** [comment]
fulibFx doesn't modify the position of the modal stage at all, so this is probably JavaFX related.
When using the new modal builder, `show()` returns the modal stage object. 
Could you try using this instance to set the position, after `show()` has been called?

**Comment by LeStegii** [comment]
What also just came to my mind is that when I wrote a JavaFX application a while ago, we had some problems with centering the modal on linux (Ubuntu), so this could also be an OS problem, even though this is less likely.

**Comment by Baldi-OG** [comment]
I will try using the instance to set the position after calling show().
I also considered if it was an OS problem, but since other participants of stp, who are using windows, encountered similar problems it seems not to be the case.

**Comment by LeStegii** [comment]
Closing this, since it isn't a fulibFx issue.
