### ISSUE TITLE
Overriden annotated methods result in unexpected behaviour

### ISSUE THREAD

**Issue by LeStegii** [fujaba/fulibFx#86]
**Describe the bug**
When using a super class for a controller, it will be scanned for methods annotated with `@OnXY`.
If the super class contains a method `xy()` annotated with `@OnXY` and the sub class (controller) overrides the same method (even without calling super) and is annotated with `@OnXY`, the sub class method will be called twice.

```java
class Parent {

    @OnDestroy
    void onDestroy() {
        System.out.println("parent");
    }
}

class Child extends Parent {

    @OnDestroy
    void onDestroy() {
        System.out.println("child");
    }
}
```

This results in "child" being printed twice upon destroying the controller.

**Expected behavior**
One would expect that both methods are called and "child" and "parent" are printed.

**Additional context**
This is caused by the annotation processor thinking that these methods are independend.
I don't think this is worth fixing, but it should be noted somewhere (maybe using the annotation processor).
![grafik](https://github.com/fujaba/fulibFx/assets/50475262/3b8eb796-d048-485e-9d41-60fbd9cc43c7)

**Comment by Clashsoft** [comment]
I thought about this, but forgot. Thanks for writing it down. I think the best solution is to call the method once, and rely on users to call super.init() if they want that. The problem is the implementation, we will need to check for every method if it overrides/is overriden.

**Comment by LeStegii** [comment]
When loading/compiling a controller, we could check if there is a method with the same name and annotation in the super class(es).
As we loop through them already, it shouldn't require to much additional workload.
